version: "3.8"

services:
  db:
    image: postgres:15
    container_name: marketease-postgres
    restart: always
    environment:
      POSTGRES_DB: marketease
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blaster5505
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: marketease-backend
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: marketease-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
