version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: marketease
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blaster5505
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ..
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: blaster5505
      DB_NAME: marketease
      DB_SSLMODE: disable
      JWT_SECRET: your_super_secret_key
    entrypoint: [ "sh", "-c", "sleep 10 && ./server" ]

volumes:
  postgres_data:
